package com.lunacygames.thelastarmada.gameutils;

/**
 * Created by zeus on 3/9/15.
 */
public enum GameStateList {
    INIT,
    TITLE_SCREEN,
    GAME_MENU,
    OVERWORLD,
    LOAD_MAP,
    TO_BATTLE,
    TO_BOSS_BATTLE,
    BATTLE,
    BOSS_BATTLE,
    GAME_OVER_LOSS,
    BATTLE_VICTORY,
    LOAD_OVERWORLD_UI,
    TO_BATTLE_EFFECT, TO_MENU, SAVE_GAME, BATTLE_VICTORY_SCREEN, TO_GAME_OVER, GAME_OVER_LOSS_A, GAME_TBC, TO_GAME_TBC, BATTLE_VICTORY_SCREEN_A, GAME_OVER_WIN
}
